spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/vessel_ems
spring.datasource.username=vessel_user
spring.datasource.password=Vessel127
spring.datasource.driver-class-name=org.postgresql.Driver