version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: vesselems-backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/vessel_ems
      SPRING_DATASOURCE_USERNAME: vessel_user
      SPRING_DATASOURCE_PASSWORD: Vessel127
    ports:
      - "8080:8080"
    networks:
      - vesselems-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: vesselems-frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - vesselems-network

networks:
  vesselems-network:
    driver: bridge