spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/worklist_db
spring.datasource.username=worklist_app
spring.datasource.password=Worklist127
spring.datasource.driver-class-name=org.postgresql.Driver