spring.datasource.url=jdbc:postgresql://frp-arm.com:65512/vessel_ems
spring.datasource.username=vessel_user
spring.datasource.password=Vessel127
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update